<a href="https://colab.research.google.com/github/ashrotd/AIClassifierModel/blob/main/data_loader%26customTransforms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Loop for the epochs
#loop for all the batches
#Examples 100 samples, batch_size=20 --> 100/20=5 iterations for 1 epochs

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math

In [27]:
class WineDataSet(Dataset):
  def __init__(self):
    #data loading
    xy = np.loadtxt('wine.csv', delimiter=",",dtype=np.float32,skiprows=1)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]])
    self.n_samples = xy.shape[0]

  def __getitem__(self,index):
    #dataset[0]
    return self.x[index]

  def __len__(self):
    #len(dataset)
    return self.n_samples

In [28]:
dataset = WineDataSet()

In [29]:
dataset[0]

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])

In [30]:
a = np.loadtxt('wine.csv', delimiter=',',dtype=np.float32,skiprows=1)

In [31]:
a

array([[1.000e+00, 1.423e+01, 1.710e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.000e+00, 1.320e+01, 1.780e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.000e+00, 1.316e+01, 2.360e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [3.000e+00, 1.327e+01, 4.280e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [3.000e+00, 1.317e+01, 2.590e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [3.000e+00, 1.413e+01, 4.100e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], dtype=float32)

In [32]:
x = a[:,1:]

In [33]:
y = a[:,[0]]

In [34]:
y.shape

(178, 1)

In [60]:
class WineDatasetPrep(Dataset):
  def __init__(self):
    xy = np.loadtxt('wine.csv', delimiter=',',dtype=np.float32,skiprows=1)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]])
    self.n_samples = xy.shape[0]

  def __getitem__(self,index):
    return self.x[index], self.y[index]

  def __len__(self):
    return self.n_samples

In [70]:
dataset = WineDatasetPrep()

In [75]:
dataloader = DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)

In [76]:
dataiter = iter(dataloader)

In [14]:
#Training Loop
num_epochs = 2
total_samples = len(data)
n_iteration = math.ceil(total_samples/4)

  

In [22]:
for epoch in range(num_epochs):
  for i, (inputs,labels) in enumerate(dataloader):
    #forward and backward pass and update the weights
    if (i+1)%5==0:
      print(f'Epoch {epoch+1}/{num_epochs}, step{i+1}/{n_iteration},inputs {inputs.shape}')

Epoch 1/2, step5/45,inputs torch.Size([4, 13])
Epoch 1/2, step10/45,inputs torch.Size([4, 13])
Epoch 1/2, step15/45,inputs torch.Size([4, 13])
Epoch 1/2, step20/45,inputs torch.Size([4, 13])
Epoch 1/2, step25/45,inputs torch.Size([4, 13])
Epoch 1/2, step30/45,inputs torch.Size([4, 13])
Epoch 1/2, step35/45,inputs torch.Size([4, 13])
Epoch 1/2, step40/45,inputs torch.Size([4, 13])
Epoch 1/2, step45/45,inputs torch.Size([2, 13])
Epoch 2/2, step5/45,inputs torch.Size([4, 13])
Epoch 2/2, step10/45,inputs torch.Size([4, 13])
Epoch 2/2, step15/45,inputs torch.Size([4, 13])
Epoch 2/2, step20/45,inputs torch.Size([4, 13])
Epoch 2/2, step25/45,inputs torch.Size([4, 13])
Epoch 2/2, step30/45,inputs torch.Size([4, 13])
Epoch 2/2, step35/45,inputs torch.Size([4, 13])
Epoch 2/2, step40/45,inputs torch.Size([4, 13])
Epoch 2/2, step45/45,inputs torch.Size([2, 13])


In [23]:
class DatasetPrep(Dataset):
  def __init__(self):
    xy = np.loadtxt('wine.csv',delimiter=',',skiprows=1, dtype=np.float32)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]])
    self.n_samples = xy.shape[0]

  def __getitem__(self,index):
    return self.x[index],self.y[index]

  def __len__(self):
    return self.n_samples


In [24]:
data = DatasetPrep()

In [25]:
dataloader = DataLoader(dataset=data,batch_size=4,shuffle=True,num_workers=2)

In [26]:
for batch in dataloader:
  print(batch)

[tensor([[1.3400e+01, 4.6000e+00, 2.8600e+00, 2.5000e+01, 1.1200e+02, 1.9800e+00,
         9.6000e-01, 2.7000e-01, 1.1100e+00, 8.5000e+00, 6.7000e-01, 1.9200e+00,
         6.3000e+02],
        [1.1840e+01, 8.9000e-01, 2.5800e+00, 1.8000e+01, 9.4000e+01, 2.2000e+00,
         2.2100e+00, 2.2000e-01, 2.3500e+00, 3.0500e+00, 7.9000e-01, 3.0800e+00,
         5.2000e+02],
        [1.2720e+01, 1.8100e+00, 2.2000e+00, 1.8800e+01, 8.6000e+01, 2.2000e+00,
         2.5300e+00, 2.6000e-01, 1.7700e+00, 3.9000e+00, 1.1600e+00, 3.1400e+00,
         7.1400e+02],
        [1.3880e+01, 1.8900e+00, 2.5900e+00, 1.5000e+01, 1.0100e+02, 3.2500e+00,
         3.5600e+00, 1.7000e-01, 1.7000e+00, 5.4300e+00, 8.8000e-01, 3.5600e+00,
         1.0950e+03]]), tensor([[3.],
        [2.],
        [2.],
        [1.]])]
[tensor([[1.3720e+01, 1.4300e+00, 2.5000e+00, 1.6700e+01, 1.0800e+02, 3.4000e+00,
         3.6700e+00, 1.9000e-01, 2.0400e+00, 6.8000e+00, 8.9000e-01, 2.8700e+00,
         1.2850e+03],
        [1.3640e+0

In [41]:
class DataMake(Dataset):
  def __init__(self, transform=None):
    xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32,skiprows=1)
    self.x = xy[:,1:]
    self.y = (xy[:,[0]])
    self.n_samples = xy.shape[0]
    self.transform = transform

  def __getitem__(self,index):
    sample = self.x[index],self.y[index]
    if self.transform:
      sample = self.transform(sample)
    return sample
  def __len__(self):
    return self.n_samples

In [62]:
class ToTensor:
  def __call__(self,sample):
    inputs, targets = sample
    return torch.from_numpy(inputs), torch.from_numpy(targets)

In [63]:
data = DataMake(transform=ToTensor())
first_data = data[0]


In [64]:
class MulTransform:
  def __init__(self,factor):
    self.factor=factor
  def __call__(self,sample):
    inputs, targets = sample
    inputs *= self.factor
    return inputs, targets

In [65]:
features, labels = first_data
print(features)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])


In [66]:
type(features)

torch.Tensor

In [67]:
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(2)])
dataset = DataMake(transform=composed)


In [68]:
first_data = dataset[0]
features,labels = first_data
print(type(features))
print(type(labels))
print(features)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
