<a href="https://colab.research.google.com/github/ashrotd/AIClassifierModel/blob/main/softmax%26Cross_Entropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn
import numpy as np

In [4]:
def softmax(x):
  return np.exp(x)/np.sum(np.exp(x), axis=0)

In [5]:
x = np.array([2.0,1.0,0.1])
outputs = softmax(x)
print(np.exp(x))
print(np.sum(np.exp(x),axis=0))
outputs

[7.3890561  2.71828183 1.10517092]
11.212508845465344


array([0.65900114, 0.24243297, 0.09856589])

In [6]:
x = torch.tensor([2.0,1.0,0.1])
outputs = torch.softmax(x,dim=0)
outputs

tensor([0.6590, 0.2424, 0.0986])

In [7]:
#crossentropy Implementation
def crossentropy(actual,predicted):
  loss = -np.sum(actual*np.log(predicted))
  return loss

In [8]:
Y = np.array([1,0,0])
Y_pred = np.array([0.7,0.2,0.1])
Y_pred2 = np.array([0.1,0.3,0.6])
l1 = crossentropy(Y,Y_pred)
l2 = crossentropy(Y,Y_pred2)
l2

2.3025850929940455

In [9]:
loss = nn.CrossEntropyLoss()

In [10]:
Y = torch.tensor([0])
#n_samplesXn_classes = 1X3
Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])
l1 = loss(Y_pred_good,Y)
l2 = loss(Y_pred_bad,Y)
print(l1.item())
print(l2.item())

0.4170299470424652
1.840616226196289


In [11]:
_,predictions = torch.max(Y_pred_good,1)
 

In [13]:
Y = torch.tensor([2,0,1])
Y_pred_g = torch.tensor([[.1,1.0,2.1],[2.0,1.0,0.1],[0.1,3.0,0.1]])
Y_pred_bad = torch.tensor([[2.1,1.0,0.1],[0.1,1.0,2.1],[0.1,3.0,0.1]])
l1 = loss(Y_pred_g,Y)
l2 = loss(Y_pred_bad,Y)
print(l1.item())
print(l2.item())

0.3018244206905365
1.6241613626480103


In [14]:
torch.max(Y_pred_g,1)

torch.return_types.max(
values=tensor([2.1000, 2.0000, 3.0000]),
indices=tensor([2, 0, 1]))

In [24]:
class NeuralNet(nn.Module):
  def __init__(self,input_dims, hidden_size,num_classes):
    super(NeuralNet,self).__init__()

    self.linear1 = nn.Linear(input_dims,hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hidden_size,1)

  def forward(self,x):
    out = self.linear1(x)
    out = self.relu(out)
    out = self.linear2(out)

    y_pred = torch.sigmoid(out)
    return y_pred

In [25]:
model = NeuralNet(input_dims = 28*28,hidden_size=5,num_classes=3)

In [22]:
loss = nn.CrossEntropyLoss()